### ISSUE TITLE
Handle inkscape svgs

### ISSUE THREAD

**Issue by rsheeter** [googlefonts/picosvg#164]
picosvg fails on https://upload.wikimedia.org/wikipedia/commons/f/ff/Flag_of_Serbia.svg because:

1) viewbox isn't int (viewBox="0 0 756.13 504.09")
2) There is content from other namespaces, which we could probably just drop, such as `<sodipodi:namedview>` and `<path inkscape:connector-curvature`
3) We don't delete https://developer.mozilla.org/en-US/docs/Web/SVG/Element/metadata elements

**Comment by yisibl** [comment]
Now we have removed `metadata` in https://github.com/googlefonts/picosvg/commit/dd3b1d8923a0e82262477c016c70e20ed605d1a3

**Comment by rsheeter** [comment]
Confirmed the referenced Flag of Serbia now picosvgs
