### ISSUE TITLE
support xlink:href attributes in gradient elements

### ISSUE THREAD

**Issue by anthrotype** [googlefonts/picosvg#191]
the gradients in [emoji_u1f1eb_1f1f0.svg](https://github.com/googlefonts/noto-emoji/blob/svg_flags2/third_party/region-flags/waved-svg/emoji_u1f1eb_1f1f0.svg) use `xlink:href` to inherit from a base gradient (which does set userSpaceOnUse) which contains some stops; they only override some other attributes and have no stops of their own. It's an ingenious approach that we had not encounted yet.

```xml
  <defs>
    <linearGradient id="gradbase" gradientUnits="userSpaceOnUse">
      <stop stop-color="#a43907" stop-opacity="0.9961" offset="0"/>
      <stop stop-color="#fff" offset="1"/>
    </linearGradient>
    <linearGradient id="grad1" xlink:href="#gradbase" x1="826.45044" y1="419.93194" x2="786.12402" y2="396.11032"/>
    <linearGradient id="grad2" xlink:href="#gradbase" x1="851.56865" y1="436.06697" x2="763.03312" y2="419.67318"/>
[...]
```

picosvg should do the right thing and use the inherited attributes and stop elements from the template gradient referenced from xlink:href:

https://www.w3.org/TR/SVG/pservers.html#LinearGradientElementHrefAttribute

**Comment by yisibl** [comment]
I recently reached the end of this problem, Adobe illustrator derived SVG time meeting parallel change and generation `xlink: href`.

**Comment by anthrotype** [comment]
what do you mean? 

Have you tried with this https://github.com/googlefonts/picosvg/pull/199?

**Comment by yisibl** [comment]
I also encountered this problem, #199 can be fixed, thanks.
