### ISSUE TITLE
transform on element referencing clip-path affect how clipPath is applied

### ISSUE THREAD

**Issue by anthrotype** [googlefonts/picosvg#200]
A clipPath coordinates are interpreted using the current coordinate system of the element that references it via clip-path. An element's coordinates can be transformed via `transform`, but picosvg is ignoring this when applying clip paths, leading to incorrect results as show in the example below.

According to the SVG spec, https://www.w3.org/TR/SVG11/masking.html#EstablishingANewClippingPath

> If clipPathUnits="userSpaceOnUse", the contents of the ‘clipPath’ represent values in the current user coordinate system in place at the time when the ‘clipPath’ element is referenced (i.e., the user coordinate system for the element referencing the ‘clipPath’ element via the ‘clip-path’ property). [...]
If attribute ‘clipPathUnits’ is not specified, then the effect is as if a value of 'userSpaceOnUse' were specified.

(We currently don't support `clipPathUnits="objectBoundingBox"`, so ignore the latter for now)

When a shape has a `transform` attribute, that's equivalent to establishing a new user coordinate system, transformed by the given affine matrix. Now, if that same shape also references a `clipPath` element via `clip-path="url(#...)"` attribute (and the referenced clipPath has userSpaceOnUse), the expected rendering should be that 

1) the shape is intersected with the referenced clipPath
2) the transform is applied the clipped result

However, currently picosvg does the opposite of that. It first applies the transformation to the path coordinates, keeping the referenced clipPath unchanged, and then it intersects the transformed shape with the referenced clip-path.

This produces incorrect results like the example below.

Source SVG:

```xml
<svg xmlns="http://www.w3.org/2000/svg" height="1000" width="1000" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 4 4">
  <clipPath id="clip">
    <rect width="3" height="3"/>
  </clipPath>
  <rect width="4" height="4" fill="none" stroke="red" stroke-width="0.1"/>
  <circle cx="3" cy="3" r="2" transform="translate(-1 -1)" clip-path="url(#clip)"/>
</svg>
```

Correct rendering of source SVG:

<img width="200" alt="transform-clip-path-before" src="https://user-images.githubusercontent.com/6939968/113334339-7f0eab80-931b-11eb-92be-d2d01368af16.png">

Incorrect rendering after SVG converted via picosvg:

<img width="200" alt="transform-clip-path-pico" src="https://user-images.githubusercontent.com/6939968/113334338-7e761500-931b-11eb-80b4-01d3c9d3ea52.png">

If we change the order in which we perform the two operations, then the example above gets fixed, e.g. 

```diff
diff --git a/src/picosvg/svg.py b/src/picosvg/svg.py
index c179593..cd29dc3 100644
--- a/src/picosvg/svg.py
+++ b/src/picosvg/svg.py
@@ -1008,8 +1008,8 @@ class SVG:
         self.ungroup(inplace=True)
         # stroke after ungroup to apply group strokes properly
         self.strokes_to_paths(inplace=True)
-        self.apply_transforms(inplace=True)
         self.apply_clip_paths(inplace=True)
+        self.apply_transforms(inplace=True)
         self.evenodd_to_nonzero_winding(inplace=True)
         self.remove_unpainted_shapes(inplace=True)
         self.normalize_opacity(inplace=True)
```

... _but_ then other tests fail, specifically those related to un-grouping with multiple nested children. The test file`ungroup-multiple-children-before.svg` contains `<use>` elements with differing `x` values (which are equivalent to a `transform="translate(x)"`) as well as nested clip-paths.

The naive way in which we do the un-grouping for inherit clip-path attributes does not take into account the fact that intervening `transform` attributes will modify the coordinate system as the clip-path gets used. We are currently performing this inheritance (from a parent group to child element) of transform and clip-path attributes independently from one another: we concatenate the transforms from top to current child element, and at the same time we compute the intersection of all the clip-paths that apply to the current child, without taking into account the change of coordinate system that may occur as result of transform. But the two attributes affect each other as I have shown above..

This is quite tricky, I don't have a solution right now.

**Comment by anthrotype** [comment]
This issue is similar to https://github.com/googlefonts/picosvg/issues/110, where the application of the transforms on the shapes but not also on the gradients that are referenced by those shapes leads to incorrect rendering.

**Comment by anthrotype** [comment]
We just can't do the naive un-group operation for transform/clip-path attributes in isolation, then apply the transforms on the shapes only, and then apply the clip paths, as three independent operations. If we want to remove the groups where there are both transform and clip-path involved, we must do this in a single pass.
Basically we'd need to traverse the tree, keeping track of the current transform as we go along, and apply that transform not only to the shapes but also to any clip-paths these may reference.
There's also the option to keep the groups that have transform and/or clip-path, and convert those in the nanoemoji COLRv1 pipeline to equivalent PaintTransform -> PaintGlyph -> PaintColrLayers -> ... but I don't think we want to go that way.

**Comment by rsheeter** [comment]
Another example
![image](https://user-images.githubusercontent.com/6466432/118759842-a287aa00-b826-11eb-8357-88984af9a057.png)


> traverse the tree, keeping track of the current transform as we go along, and apply that transform not only to the shapes but also to any clip-paths these may reference

Agreed. Starting by just rigging a basic test in https://github.com/googlefonts/picosvg/tree/ungroup. To your point f2f we could also keep the clip via PaintGlyph but ... I think lets perhaps not start there.
