### ISSUE TITLE
No setting and explicit default are indistinguishable

### ISSUE THREAD

**Issue by rsheeter** [googlefonts/picosvg#224]
After pass from/to element the fill value is dropped so we can't tell that the first one should be black and the second one should inherit fill none. This complicates #223; splitting into it's own issue because I don't think it's worth blocking on.

```
  <g opacity="1" fill="none">
    <ellipse cx="85" cy="50" rx="10" ry="5" fill="black"/>
    <ellipse cx="85" cy="60" rx="10" ry="5"/>
  </g>
```

**Comment by anthrotype** [comment]
ooof.. hm.. defaults.. 🤔

**Comment by anthrotype** [comment]
basically all the fields that can be inherited should be Optional so that we can tell whether they are explicitly set on the given instance or not. I don't see other way

**Comment by anthrotype** [comment]
but.. if we do that, then every time we use those optional fields we have to check for None or else pytype will be angry
