### ISSUE TITLE
Handle objectBoundingBox gradients

### ISSUE THREAD

**Issue by rsheeter** [googlefonts/picosvg#226]
#223 improves processing somewhat but does not result in correct handling of gradients with objectBoundingBox. Uncomment the objectBoundingBox tests in `svg_test.py` and fix. 

Ref https://github.com/googlefonts/nanoemoji/blob/6675c6fd0d11dc7aece5fda779ef25c1b7291071/src/nanoemoji/color_glyph.py#L91-L112

**Comment by anthrotype** [comment]
I have a WIP patch that that fixes this, I'll push next week after I clean it up
