### ISSUE TITLE
Failed to extract translation

### ISSUE THREAD

**Issue by vXBaKeRXv** [googlefonts/picosvg#239]
.local/lib/python3.7/site-packages/picosvg/svg_transform.py", line 339, in decompose_translation
    ), f"Failed to extract translation from {self}, parts compose back to {test_compose}"
AssertionError: Failed to extract translation from Affine2D(a=-4.382842e-08, b=1.0027, c=-4.2262, d=-1.847346e-07, e=1133.4812, f=889.4797), parts compose back to Affine2D(a=-4.382842e-08, b=1.0027, c=-4.2262, d=-1.847346e-07, e=1133.4812, f=889.4796970082031)

**Comment by anthrotype** [comment]
hm, maybe we should relax that assert a bit, or remove it altogether.
Currently it checks the original and re-composed transform are almost equal up to 1e-5 decimals:

https://github.com/googlefonts/picosvg/blob/e58d1e7876f8ed151172acc59bceae8096b2cd27/src/picosvg/svg_transform.py#L35

If I set that constant to 1e-4 the almost equality check passes and the assertion error doesn't trigger.

```python
>>> t = Affine2D(a=-4.382842e-08, b=1.0027, c=-4.2262, d=-1.847346e-07, e=1133.4812, f=889.4797)
>>> t.decompose_translation()
(Affine2D(a=1, b=0, c=0, d=1, e=887.0845192597527, f=-268.2034070511364),
 Affine2D(a=-4.382842e-08, b=1.0027, c=-4.2262, d=-1.847346e-07, e=0, f=0))
```

**Comment by rsheeter** [comment]
Even 1e-3 is probably ok
