### ISSUE TITLE
Fix use + clippath

### ISSUE THREAD

**Issue by rsheeter** [googlefonts/picosvg#26]
#23 fixes issues with reversed order in ungrouping but reveals that my hand-written "right answer" and what the browser yields are different. Filing this to track correcting that. Will merge #23 because it makes things significantly better despite not being completely correct.

**Comment by anthrotype** [comment]
@rsheeter I forgot what exactly the issue was here. If you remember, can you elaborate a bit?

**Comment by rsheeter** [comment]
I'm not quite clear what this was about lolz.
