### ISSUE TITLE
picosvg "bag of money" emoji makes invisible paths appear

### ISSUE THREAD

**Issue by anthrotype** [googlefonts/picosvg#260]
https://github.com/googlefonts/noto-emoji/blob/main/svg/emoji_u1f4b0.svg
![emoji_u1f4b0](https://user-images.githubusercontent.com/6939968/151424851-3dfdb758-253e-420b-a130-9c1370fbd912.png)
![emoji_u1f4b0_2](https://user-images.githubusercontent.com/6939968/151424866-4aae0658-3165-4b5b-9370-56e6cb24bea3.png)

**Comment by anthrotype** [comment]
the svg file contains groups with display="none", which in turn contain some shapes with display="inline". I think picosvg is applying its normal inerit-copy rules for display attribute, so the children with display:inline override the display:none of the parent and thus become visible again..

However see https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/display

> When applied to a container element, setting display to none causes the container and all of its children to be invisible; thus, it acts on groups of elements as a group. This means that any child of an element with display="none" will never be rendered even if the child has a value for display other than none.

**Comment by rsheeter** [comment]
Oh My
