### ISSUE TITLE
topicosvg of pathops-tricky-path-before.svg doesn't always work

### ISSUE THREAD

**Issue by rsheeter** [googlefonts/picosvg#299]
Run pytest on unmodified main in a new venv on Google Linux. We have a test failure: `FAILED tests/svg_test.py::test_topicosvg[pathops-tricky-path-before.svg-pathops-tricky-path-nano.svg] - assert '<svg xmlns="..."/>\n</svg>\n' == '<svg xmlns="..."/>\n</svg>\n'`

**Comment by anthrotype** [comment]
I released new skia-pathops a few days ago (also updated embedded libskia to chrome/m113), the CI breakages are probably related to that. I think we just need to update the expected results.

**Comment by anthrotype** [comment]
python 3.7 is EOL so most packages (including skia-pathops) have dropped support, we should do the same for picosvg and nanoemoji for the next release
