### ISSUE TITLE
non-path related attributes get lost when applying transform or stroke via svg_pathops

### ISSUE THREAD

**Issue by anthrotype** [googlefonts/picosvg#32]
When we pass an SVGShape through either svg_pathops.transform or svg_pathops.stroke, we need to roundtrip from SVGShape to SkPath and back to SVGShape.
However the problem is, since SkPath only holds info about the path proper, and has no knowledge of fill, opacity, id, etc., we are losing all those extra non-path-related attributes when performing either transform or stroke.

When running transform and stroke operations via skia we need to restore the rest of the SVGShape attributes, copying them from the input original SVGShape. For transform operation, we of course should skip the transform attribute that we just applied; similarly for stroke-related attrs when stroking.

I believe for clipping operations (union, intersection) we probably don't need to bother copying these, since we run these on clip paths which are kind of special and limited sort of paths. It's also unclear from which of the input shapes the result of a union or intersection would inherit from.

**Comment by rsheeter** [comment]
stroke looks to me like it already copies attributes around. transform definitely does not.

**Comment by rsheeter** [comment]
...stroke is missing some copying too, adding a test to demonstrate
