### ISSUE TITLE
fill-rule, clip-rule evenodd not supported, used by twemoji

### ISSUE THREAD

**Issue by rsheeter** [googlefonts/picosvg#52]
```shell
W0615 21:19:04.836112 4542711232 nanoemoji.py:163] SVG.parse(font-srcs/twemoji/assets/svg//1f1e8-1f1fe.svg) failed: Unable to process group attrib {'fill-rule': 'evenodd', 'clip-rule': 'evenodd'}
W0615 21:19:13.307007 4542711232 nanoemoji.py:163] SVG.parse(font-srcs/twemoji/assets/svg//1f1f1-1f1f8.svg) failed: Unable to process group attrib {'fill-rule': 'evenodd', 'clip-rule': 'evenodd'}
W0615 21:19:14.117563 4542711232 nanoemoji.py:163] SVG.parse(font-srcs/twemoji/assets/svg//1f1f2-1f1f4.svg) failed: Unable to process group attrib {'fill-rule': 'evenodd', 'clip-rule': 'evenodd'}
I0615 21:19:19.862827 4542711232 nanoemoji.py:504] 3242/3245 inputs prepared successfully
```

**Comment by anthrotype** [comment]
skia-pathops `Path` object has a `fillType` property getter/setter, it defaults to `FillType.WINDING` (non-zero winding). 

https://github.com/fonttools/skia-pathops/blob/6581155e5151624ae9756392db025810933b74d6/src/python/pathops/_pathops.pyx#L305

We can set it to `FillType.EVEN_ODD` and I think this should then work as expected.

https://github.com/fonttools/skia-pathops/blob/6581155e5151624ae9756392db025810933b74d6/src/python/pathops/_pathops.pxd#L42

**Comment by anthrotype** [comment]
the SVG spec says 

> The clip-rule attribute only applies to graphics elements that are contained within a <clipPath> element. 

there is even an example where the clip-rule is outside of clipPath, and this

> will not cause an evenodd clipping rule to be applied because the clip-rule is specified on the referencing element, not on the object defining the clipping shape

https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/clip-rule

I checked our test SVG files in both noto-emoji and twemoji, and _none_ of the `clip-rule` uses occur within a `clipPath`, they all occur outside, so they are basically ignored and never used.

I used this script to grep for clip-rule inside clipPath elements:

```python
import sys
import glob
from pprint import pprint
from lxml import etree


svg_directory = sys.argv[1]


def contains_cliprule_attrib(element):
    if "clip-rule" in element.attrib:
        return True
    for el in element.iter():
        if "clip-rule" in el.attrib:
            return True
    return False


all_cliprule_files = set()
invalid_cliprule_files = set()

for filename in glob.glob(f"{svg_directory}/*.svg"):
    tree = etree.parse(filename)
    svg = tree.getroot()

    has_cliprule = contains_cliprule_attrib(svg)
    if not has_cliprule:
        continue

    all_cliprule_files.add(filename)

    cliprule_inside_clippath = False
    for clip_path in svg.xpath(
        "//svg:clipPath", namespaces={"svg": "http://www.w3.org/2000/svg"}
    ):
        if contains_cliprule_attrib(clip_path):
            cliprule_inside_clippath = True
            break

    if not cliprule_inside_clippath:
        invalid_cliprule_files.add(filename)


print(len(all_cliprule_files))
pprint(all_cliprule_files)

print(len(invalid_cliprule_files))
pprint(invalid_cliprule_files)

valid_cliprules_files = all_cliprule_files - invalid_cliprule_files
print(len(valid_cliprules_files))
pprint(valid_cliprules_files)
```
